config/routes.rb
Rails.application.routes.draw do
  get "reservations/index" => "reservations#index"
  post "reservations/confirm" => "reservations#confirm"
  patch "users/update" => "users#update"
  get "rooms/own" => "rooms#own"
  get "search" => "rooms#search"
  resources :rooms, :reservations
  root to: "homes#top"
  get "users/profile" => "users#profile"
  devise_for :users
  get "users/index" => "users#index"
  get "users/:id/show" => "users#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord

    belongs_to :room, class_name: "Room", foreign_key: "room_id", optional: true
    belongs_to :user, class_name: "User", foreign_key: "user_id", optional: true

    validates :check_in, presence: true
    validates :check_out, presence:true
    validates :person, presence: true
    validate :start_end_check

    def start_end_check
        if self.check_in.nil? || self.check_out.nil?
            errors.add(:check_in, :check_out)
        elsif self.check_in >= self.check_out
            errors.add(:check_out)
        end
    end

end

app/models/room.rb
class Room < ApplicationRecord

    has_many :reservations, class_name: "Room", foreign_key: "room_id"
    belongs_to :user, class_name: "User", foreign_key: "user_id", optional: true

    validates :name, presence: true
    validates :detail, presence: true
    validates :price, presence: true
    validates :address, presence: true

    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true


  mount_uploader :image, ImageUploader
  has_many :rooms, class_name: "Room", foreign_key: "user_id"
  has_many :reservations, class_name: "Reservation", foreign_key: "user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller? 
    
    def after_sign_in_path_for(resource)
        "/"
    end
    private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email, :introduction])
      devise_parameter_sanitizer.permit(:account_update,keys:[:name, :email, :introduction, :image])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:check_in, :check_out, :person, :user_id, :room_id))
    if @reservation.save
      flash[:notice] = "登録しました"
      redirect_to "/reservations"
    else
      flash[:notice] = "登録に失敗しました"
      render room
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    redirect_to :reservations
  end

  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:check_in, :check_out, :person, :user_id, :room_id))
    @user = current_user
    if @reservation.check_in.nil? || @reservation.check_out.nil? || @reservation.person.nil? || @reservation.check_in >= @reservation.check_out
      flash[:notice] = "入力内容に不備があります"
      redirect_back(fallback_location: root_path)
    end
  end


  private
    def permit_params
      @attr = params.require(:reservation).permit(:check_in, :check_out, :person, :user_id, :room_id)
    end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :own]
  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
    @room = Room.find_by(id: params[:id])
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
    @user = current_user
    @reservation = Reservation.new
    @reservation.room_id = @room.id
  end

  # GET /rooms/new
  def new
    @user = current_user
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @user = current_user
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(params.require(:room).permit(:name, :detail, :price, :address, :image, :user_id))
    @room.user_id = current_user.id
    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "施設が登録されました" }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "施設情報が更新されました" }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "施設が削除されました" }
      format.json { head :no_content }
    end
  end

  def own
    @rooms = Room.where(user_id: current_user)
  end

  def search
    @area = params[:area]
    @keyword = params[:keyword]
    if @area.present?
      @rooms = Room.where(["address like?", "%#{params[:area]}%"])
    else @keyword.present?
      @rooms = Room.where(["name like? OR detail like?", "%#{params[:keyword]}%", "%#{params[:keyword]}%"])
    end
    render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :detail, :price, :address, :image)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show, :profile, :update]
    def index
    end
    
    def show
        @user = User.find_by(id: params[:id])
    end

    def profile
        @user = current_user
    end

    def update
        @user = current_user
        if @user.update(params.require(:user).permit(:image, :name, :introduction))
            flash[:notice] = "更新しました"
            redirect_to "/users/#{current_user.id}/show"
        else
            flash[:notice] = "登録に失敗しました"
            render "profile"
        end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="first_view">
    <div class="first_view_container">
        <h2 class="first_view_title">Potepan Shareで<br>
            まだ体験したことのない<br>
            旅をしよう
        </h2>
        <div class="first_view_search">
            <%= form_with url: search_path, method: :get, local: true do |f| %>
                <%= f.text_field :area, class: "search_form", placeholder: "エリア名を入力" %>
                <%= f.submit "検索" %>
            <% end %>
        </div>
    </div>
</div>
<div class="first_view_main">
    <h2>おすすめのエリア</h2>
    <div class="first_view_card">
        <a href="http://localhost:3000/search?area=%E6%9D%B1%E4%BA%AC&commit=%E6%A4%9C%E7%B4%A2" class="card tokyo_card" style="width: 18rem;">東京</a>
        <a href="http://localhost:3000/search?area=%E5%A4%A7%E9%98%AA&commit=%E6%A4%9C%E7%B4%A2" class="card osaka_card" style="width: 18rem;">大阪</a>
        <a href="http://localhost:3000/search?area=%E4%BA%AC%E9%83%BD&commit=%E6%A4%9C%E7%B4%A2" class="card kyoto_card" style="width: 18rem;">京都</a>
        <a href="http://localhost:3000/search?area=%E6%9C%AD%E5%B9%8C&commit=%E6%A4%9C%E7%B4%A2" class="card sapporo_card" style="width: 18rem;">札幌</a>
        
    </div>
</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation_app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="header">
      <%= link_to("Potepan Share", "/", class: "top_logo") %>
      <nav>
        <% if user_signed_in? %>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle", style="color: white;" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li><%= link_to("施設の新規登録", new_room_path, class: "dropdown-item top_nav_hide") %></li>
              <li><%= link_to("予約済み一覧", reservations_path, class: "dropdown-item top_nav_hide") %></li>
              <li><%= link_to("登録済み一覧", "rooms/own", class: "dropdown-item top_nav_hide") %></li>
              <li><%= link_to("アカウント設定", "/users/#{current_user.id}/show", class: "dropdown-item top_nav_hide") %></li>
              <li><%= link_to("ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item top_nav_hide") %></li>
            </ul>
          </div> 
        <% else %>
          <%= link_to("ログイン", new_user_session_path, class: "top_nav") %>
          <%= link_to("新規登録", new_user_registration_path, class: "top_nav", class: "btn btn-primary top_nav")%>
        <% end %>
      </nav>
    </div>
    <%= notice %>
    <%= alert %>
    <%= yield %>
    <div class="footer">
      <div class="footer_container">
        <%= link_to("Potepan Share", "/", class: "footer_logo") %>
        <p class="footer_message">Copyright © Potepan Share 2023 All rights reserved</p>
      </div>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/reservations/confirm.html.erb
<h1>予約内容の確認</h1>
<%= "チェックイン：#{@reservation.check_in.strftime("%Y/%m/%d")}" %><br>
<%= "チェックアウト：#{@reservation.check_out.strftime("%Y/%m/%d")}" %><br>
<%= "日数：#{(@reservation.check_out - @reservation.check_in).to_i}日" %><br>
<%= "人数：#{@reservation.person}人" %><br>
<%= "お支払い金額：¥#{@reservation.person * @reservation.room.price * (@reservation.check_out - @reservation.check_in).to_i }" %>

<%= form_with model: @reservation, url: "/reservations" do |r| %>
    <p><%= r.hidden_field :check_in %></p>
    <p><%= r.hidden_field :check_out %></p>
    <p><%= r.hidden_field :person %></p>
    <p><%= r.hidden_field :user_id, value: @user.id%></p>
    <p><%= r.hidden_field :room_id, value: @reservation.room_id %></p>
<%= r.submit "予約確定" %>  
<%= link_to("戻る", :back, class: "btn btn-primary") %>  
<% end %>

app/views/reservations/index.html.erb
<div class="reservation_index_table">
  <h1>予約済み一覧</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col">紹介文</th>
        <th scope="col">合計料金</th>
        <th scope="col">チェックイン</th>
        <th scope="col">チェックアウト</th>
        <th scope="col">予約確定日時</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
    <% if @reservation == 0 %>
      <p>予約を登録してください</p>
    <% else %>
      <% @reservations.each do |r| %>
        <tr>
          <td scope="row"><img src=<%= r.room.image %>></td>
          <td><%= r.room.name %></td>
          <td><%= r.room.detail %></td>
          <td><%= r.room.price * r.person * (r.check_out - r.check_in).to_i %></td>
          <td><%= r.check_in.strftime("%Y/%m/%d") %></td>
          <td><%= r.check_out.strftime("%Y/%m/%d") %></td>
          <td><%= r.created_at.to_s(:datetime_jp) %></td>
          <td><%= link_to("再予約", "/rooms/#{r.room.id}") %></td>
          <td><%= link_to("予約を削除", "/reservations/#{r.id}", method: :delete, data: { confirm: '本当に削除しますか？' }) %></td>
        </tr>
      <% end %>
    <% end %>  
    </tbody>
  </table>
</div>

app/views/rooms/_form.html.erb
<div class="room_form">
  <%= form_with(model: room) do |form| %>
    <% if room.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
      <div class="field mb-3">
        <%= form.label :name, class: "form-label", value: "施設名" %>
        <%= form.text_field :name, class: "form-control", placeholder: "名前を入力してください" %>
      </div>

      <div class="field mb-3">
        <%= form.label :detail, class: "form-label", value: "施設詳細" %>
        <%= form.text_area :detail, class: "form-control", placeholder: "詳細を入力してください" %>
      </div>

      <div class="field mb-3">
        <%= form.label :price, class: "form-label", value: "料金" %>
        <%= form.number_field :price, class: "form-control", placeholder: "金額を入力してください" %>
      </div>

      <div class="field mb-3">
        <%= form.label :address, class: "form-label", value: "住所" %>
        <%= form.text_area :address, class: "form-control", placeholder: "住所を入力してください" %>
      </div>

      <div>
        <%= form.label :image, value: "施設画像" %><br>
        <%= form.file_field :image %>
      </div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>施設情報の編集</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to '戻る', :back %>

app/views/rooms/index.html.erb
<div class="room_index_container">
  <div class="room_index_top">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :area, placeholder: "エリア名を入力" %>
    <%= f.text_field :keyword, placeholder: "キーワード名を入力" %>
    <%= f.submit "検索" %>
  <% end %>
  </div>
  <div class="room_index_main">
    <div class="index_count">
      <%= "#{@rooms.count}件が見つかりました。" %>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @rooms.each do |r| %>
        <div class="col">
          <div class="card">
            <img src=<%= r.image %>>
            <div class="card-body">
              <h6 class="card-title"><%= r.name %></h6>
              <p><%= r.address %></p>
              <p class="card-text"><%= r.detail %></p>
              <%= r.price %>
              <%= link_to("詳細", "/rooms/#{r.id}", class: "btn btn-primary") %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="room_form">
    <h1>新規登録</h1>

    <%= render 'form', room: @room %>

    <%= link_to '戻る', :back %>
</div>

app/views/rooms/own.html.erb
<p id="notice"><%= notice %></p>

<div class="room_index_table">
  <h1>登録済み一覧</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col">紹介文</th>
        <th scope="col">料金</th>
        <th scope="col">作成日</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td scope="row"><img src=<%= room.image %>></td>
          <td><%= link_to(room.name, room, :style => "text-decoration: none;") %></td>
          <td><%= room.detail %></td>
          <td><%= room.price %></td>
          <td><%= room.created_at.to_s(:datetime_jp) %></td>
          <td><%= link_to '編集', edit_room_path(room) %></td>
          <td><%= link_to '施設を削除', room, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/show.html.erb
<div class="room_show">
  <div class="room_show_bar">
    <%= link_to '戻る', :back, class: "btn btn-outline-primary" %>
    <%= link_to '編集', edit_room_path(@room), class: "btn btn-outline-primary" %>
  </div>
  <div class="room_show_content">
    <div class="room_show_content_left">
      <img src=<%= @room.image %>>
    </div>
    <div class="room_show_content_right">
      <h2>施設名：<%= @room.name %><br></h2>
      <p>金額：<%= @room.price %></p>
      <p>住所：<%= @room.address %><br><p>
      <p>詳細：<%= @room.detail %></p>

      <%= form_with model:@reservation, url: "/reservations/confirm" do |r| %>
        <%= r.label :check_in, "チェックイン" %><br>
        <%= r.date_field :check_in %><br>
        <%= r.label :check_out, "チェックアウト" %><br>
        <%= r.date_field :check_out %><br>
        <%= r.label :person, "人数" %><br>
        <%= r.text_field :person %><br>
        <%= r.hidden_field :user_id, value: @reservation.user_id %>
        <%= r.hidden_field :room_id, value: @reservation.room_id %>
        <%= r.submit value: "予約する", class: "btn btn-primary"%>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>indexページ</h1>

app/views/users/profile.html.erb
<h1>プロフィール</h1>

<%= form_with model: @user, url: users_update_path, method: :patch, scope: :user do |f| %>
    <div class="field">
    <%= f.label :image, value: "プロフィール画像" %><br />
    <%= f.file_field :image, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :name, value: "名前" %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :introduction, value: "自己紹介" %><br />
    <%= f.text_area :introduction, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit '更新' %>
  </div>

<% end %>

app/views/users/show.html.erb
<div class="show_container">
  <h1>設定</h1>

  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button
        class="nav-link active"
        id="nav-home-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-home"
        type="button"
        role="tab"
        aria-controls="nav-home"
        aria-selected="true"
      >
        アカウント
      </button>
      <button
        class="nav-link"
        id="nav-profile-tab"
        data-bs-toggle="tab"
        data-bs-target="#nav-profile"
        type="button"
        role="tab"
        aria-controls="nav-profile"
        aria-selected="false"
      >
        プロフィール
      </button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div
      class="tab-pane fade show active"
      id="nav-home"
      role="tabpanel"
      aria-labelledby="nav-home-tab"
    >
      <div class="account_settings">
          <div class="account_settings_top">
              <h2>アカウント</h2>
              <%= link_to("アカウント編集", edit_user_registration_path, class: "btn btn-outline-primary") %>   
          </div>
          <div class ="account_settings_main">
              <table>
                  <tr>
                      <th>メールアドレス</th>
                      <td><%= @user.email %></td>
                  </tr>
                  <tr>
                      <th>パスワード</th>
                      <td>*********</td>
                  </tr>
              </table>
          </div>
      </div>
    </div>
    <div
      class="tab-pane fade"
      id="nav-profile"
      role="tabpanel"
      aria-labelledby="nav-profile-tab"
    >
      <div class="account_settings">
          <div class="account_settings_top">
              <h2>プロフィール</h2>
              <%= link_to("プロフィール編集", "/users/profile", class: "btn btn-outline-primary") %>   
          </div>
          <div class ="account_settings_main">
              <table>
                  <tr>
                      <th>アイコン画像</th>
                      <td><img src=<%= @user.image %>></td>
                  </tr>
                  <tr>
                      <th>名前</th>
                      <td><%= @user.name %></td>
                  </tr>
                  <tr>
                      <th>自己紹介</th>
                      <td><%= @user.introduction %></td>
                  </tr>
              </table>
          </div>
      </div>
    </div>
  </div>
</div>